server {
    listen       0.0.0.0:8000;
    listen  [::]:8000;
    server_name  localhost;

    # Autoriser l'intégration dans un iframe depuis n'importe quelle origine
    add_header Content-Security-Policy "frame-ancestors 'self' localhost:8000 ;";

    # Autoriser les requêtes CORS depuis Keycloak
    # add_header Access-Control-Allow-Origin "https://keycloak-mercury.todoustudio.cloud" always;
    add_header Access-Control-Allow-Origin "localhost:8000" always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE" always;
    add_header Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization" always;



    # Répertoire racine pour servir les fichiers
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Redirection des requêtes vers index.html pour les routes SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Rediriger les pages d'erreur vers /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
